-- return {
--     "folke/noice.nvim",
--     event = "VeryLazy",
--     dependencies = {
--         -- if you lazy-load any plugin below, make sure to add proper `module="..."` entries
--         "MunifTanjim/nui.nvim",
--         -- OPTIONAL:
--         --   `nvim-notify` is only needed, if you want to use the notification view.
--         --   If not available, we use `mini` as the fallback
--         -- "rcarriga/nvim-notify",
--     },
--     config = function()
--         require("noice").setup({
--             lsp = {
--                 -- override markdown rendering so that **cmp** and other plugins use **Treesitter**
--                 override = {
--                     ["vim.lsp.util.convert_input_to_markdown_lines"] = true,
--                     ["vim.lsp.util.stylize_markdown"] = true,
--                     ["cmp.entry.get_documentation"] = true, -- requires hrsh7th/nvim-cmp
--                 },
--             },
--             cmdline = {
--                 view = "cmdline",
--             },
--             hover = {
--                 enabled = true,
--                 silent = true, -- set to true to not show a message if hover is not available
--                 view = nil, -- when nil, use defaults from documentation
--                 ---@type NoiceViewOptions
--                 opts = {
--                    
--                 }, -- merged with defaults from documentation
--             },
--             -- you can enable a preset for easier configuration
--             presets = {
--                 bottom_search = true, -- use a classic bottom cmdline for search
--                 command_palette = true, -- position the cmdline and popupmenu together
--                 long_message_to_split = true, -- long messages will be sent to a split
--                 inc_rename = false, -- enables an input dialog for inc-rename.nvim
--                 lsp_doc_border = false, -- add a border to hover docs and signature help
--             },
--         })
--         local hover = require("noice.lsp").hover
--         local opts = { noremap = true, silent = true }
--         local function my_hover(err, result, ctx, config)
--             vim.notify("my hover" .. (err or "no err") .. (result or "no result").. (ctx or "no ctx") .. (config or "no config"))
--             return hover(err, result, ctx)
--         end
--         vim.keymap.set("n", "K", my_hover, opts)
--     end,
-- }
return {}
