-- return {
--     {
--         "VidocqH/lsp-lens.nvim",
--         config = function ()
--             require('lsp-lens').setup {
--                 -- this will show the reference count of the symbol under the cursor
--                 code_lens = {
--                     enable = true,
--                     debounce = 150,
--                     text = ' %#:count references',
--                 },
--             }
--         end
--     },
-- }
return {}
