[pyprland]
plugins = ["scratchpads"]

[scratchpads.term]
command = "kitty --class scratchpad"
animation = "fromTop"
lazy = true

[scratchpads.discord]
command = "webcord"
position = "5% 5%"
lazy = true
