#!/usr/bin/env bash

options="lock\nsuspend\npoweroff\nreboot"
mode=$(echo -e "$options" | wofi --show dmenu)
echo "$mode"

case "$mode" in
"lock") hyprlock ;;
"suspend") systemctl suspend ;;
"poweroff") systemctl poweroff ;;
"reboot") systemctl reboot ;;
esac
